export class ExportService {
  constructor() {
    this.supportedFormats = ["pdf", "csv", "print"];
  }

  async export(data, format, options = {}) {
    switch (format) {
      case "csv":
        return this.exportCsv(data, options);
      case "pdf":
        return this.exportPdf(data, options);
      case "print":
        return this.exportPrint(data, options);
      default:
        throw new Error(`Unsupported export format: ${format}`);
    }
  }

  exportCsv(data, options = {}) {
    return Promise.resolve({
      format: "csv",
      filename: options.filename || "export.csv",
      content: typeof data === "string" ? data : JSON.stringify(data, null, 2),
    });
  }

  exportPdf(data, options = {}) {
    const jsPDFFactory = window.jspdf?.jsPDF ?? window.jspdf;
    if (!jsPDFFactory) {
      return Promise.reject(new Error("PDF library unavailable."));
    }

    const doc = new jsPDFFactory({ unit: "pt", format: "letter" });
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 40;
    const accent = "#3b82f6";
    const headerColor = "#0f1d3b";
    const textPrimary = "#0f172a";
    const textSecondary = "#475569";
    const sectionGap = 18;
    const rowHeight = 18;
    let y = 48;

    doc.setFillColor(headerColor);
    doc.rect(0, 0, pageWidth, 90, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor("#ffffff");
    doc.text("AXION ENGINEERING SUITE", margin, 28);
    doc.setFontSize(18);
    doc.text(data.title || "Gear Ratio Calculation Report", margin, 52);
    doc.setFontSize(10);
    doc.text(`Generated Date: ${new Date(data.generatedAt).toLocaleDateString()}`, margin, 72);
    doc.text(`Generated Time: ${new Date(data.generatedAt).toLocaleTimeString()}`, margin + 260, 72);
    doc.text(`Calculator Version: ${data.calculatorVersion || "1.0"}`, pageWidth - margin, 72, { align: "right" });

    const sectionHeader = (title) => {
      y += 30;
      doc.setDrawColor(accent);
      doc.setLineWidth(1.2);
      doc.line(margin, y, pageWidth - margin, y);
      y += 18;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(accent);
      doc.text(title, margin, y);
      y += 14;
    };

    const renderKeyValueRows = (items) => {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(textPrimary);
      items.forEach(({ label, value }) => {
        if (y > pageHeight - 90) {
          doc.addPage();
          y = margin;
        }
        doc.text(label, margin, y);
        doc.text(String(value), pageWidth - margin, y, { align: "right" });
        y += rowHeight;
      });
      y += sectionGap;
    };

    const renderFormulas = (formulas) => {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(textPrimary);
      formulas.forEach((item) => {
        if (y > pageHeight - 90) {
          doc.addPage();
          y = margin;
        }
        doc.text(item.title, margin, y);
        y += 14;
        doc.setFont("helvetica", "normal");
        doc.setTextColor(textSecondary);
        doc.text(item.equation, margin + 16, y);
        y += rowHeight;
      });
      y += sectionGap;
    };

    const renderBulletList = (items) => {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(textPrimary);
      items.forEach((item) => {
        if (y > pageHeight - 90) {
          doc.addPage();
          y = margin;
        }
        doc.text("•", margin, y);
        doc.text(item, margin + 12, y, { maxWidth: pageWidth - margin * 2 - 12 });
        y += rowHeight;
      });
      y += sectionGap;
    };

    sectionHeader("INPUT PARAMETERS");
    renderKeyValueRows(data.inputs);

    sectionHeader("CALCULATION RESULTS");
    renderKeyValueRows(data.results);

    sectionHeader("FORMULAS USED");
    renderFormulas(data.formulas);

    sectionHeader("ENGINEERING ASSUMPTIONS");
    renderBulletList(data.assumptions);

    sectionHeader("ENGINEERING NOTES");
    renderBulletList(data.notes);

    const pages = doc.getNumberOfPages();
    for (let i = 1; i <= pages; i += 1) {
      doc.setPage(i);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(textSecondary);
      doc.text("Generated by Axion Engineering Suite", margin, pageHeight - 30);
      doc.text(`Version ${data.calculatorVersion || "1.0"}`, pageWidth - margin, pageHeight - 30, { align: "right" });
      doc.text(`Page ${i} of ${pages}`, pageWidth / 2, pageHeight - 30, { align: "center" });
    }

    const blob = doc.output("blob");
    return Promise.resolve({
      format: "pdf",
      filename: options.filename || "export.pdf",
      content: blob,
    });
  }

  exportPrint(data, options = {}) {
    if (options.window) {
      options.window.print();
    }
    return Promise.resolve({ format: "print", content: data });
  }
}
